packages:
  - "resources/*"
  - "proposals/multi-tenant"
  - "proposals/single-tenant-shared-renderer/*"
  - "proposals/single-tenant-separate-renderer/renderers/*"
  - "proposals/single-tenant-separate-renderer/application"
  - "proposals/single-tenant-separate-renderer/bff"
