packages:
  - "dependencies/*"
  - "proposals/client-side-integration/brands/*"
  - "proposals/client-side-integration/*"
  - "proposals/server-side-integration/brands/*"
  - "proposals/server-side-integration/*"
